### ISSUE TITLE
Submission preparation

### ISSUE THREAD

**Issue by cvillagrasa** [antonrafael/returnName#5]
![imagen](https://user-images.githubusercontent.com/57069798/168173764-6098c35a-dd4c-4426-8d06-1c4182e6155b.png)
![imagen](https://user-images.githubusercontent.com/57069798/168173834-7fd901d9-6d4b-4eac-984b-8d2b83c79394.png)
![imagen](https://user-images.githubusercontent.com/57069798/168173853-2233d4e3-00ee-424d-9960-7f5ef59b284e.png)
![imagen](https://user-images.githubusercontent.com/57069798/168173891-b1fde4f2-dea5-4055-8359-ea467e031664.png)
![imagen](https://user-images.githubusercontent.com/57069798/168173919-f942852d-38b3-477c-8eca-bacfb49a6883.png)
![imagen](https://user-images.githubusercontent.com/57069798/168173955-ff03884f-6f4d-4c51-b191-44ae1c8dff4a.png)
![imagen](https://user-images.githubusercontent.com/57069798/168173988-182d325b-7339-433f-aa0f-ae08bef3d178.png)
![imagen](https://user-images.githubusercontent.com/57069798/168174075-8fc586ec-3b3f-4d11-abf9-a9a5b90781c9.png)
![imagen](https://user-images.githubusercontent.com/57069798/168174117-e9737328-509c-41ae-b42e-af4a0375e978.png)
![imagen](https://user-images.githubusercontent.com/57069798/168174150-85891b7a-9e1e-4ec7-a5f2-6c44124ab088.png)

**Comment by ChenChihYuan** [comment]
9.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/13364367/168420224-5ef21e5e-ae0c-41d3-8c34-eddec56c7f05.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/13364367/168420238-c740d604-c891-4e55-9600-f36c07c82b8b.png">
